apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"webhook-service","namespace":"contrail-deploy"},"spec":{"ports":[{"port":443,"protocol":"TCP","targetPort":29443}],"selector":{"app":"contrail-k8s-deployer"}}}
  creationTimestamp: "2024-02-01T17:33:49Z"
  name: webhook-service
  namespace: contrail-deploy
  uid: 4e7856e8-df8f-4a43-83c1-d3012daa08fb
spec:
  clusterIP: 10.102.246.251
  clusterIPs:
  - 10.102.246.251
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 29443
  selector:
    app: contrail-k8s-deployer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
